### ISSUE TITLE
exclude-pattern for specific rules don't work

### ISSUE THREAD

**Issue by godbout** [SublimeLinter/SublimeLinter-phpcs#19]
I was trying to avoid some rules for my tests, and although it works fine through the command line, it doesn't work through sublime. I think it's due to the fact that for whatever reason, phpcs is ran on some temp files in private/var rather than my source folders. The exclude-pattern is relative to the source.

Here are my files:

linter settings
````
"linters": {
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [
                    "*.blade.php"
                ],
                "standard": ""
            }
        },
````

phpcs.xml
````
<?xml version="1.0"?>
<ruleset name="PSR2">
 <description>Hopefully PSR2 standard that works</description>

 <rule ref="PSR2">
 </rule>

<rule ref="PSR1.Methods.CamelCapsMethodName.NotCamelCaps">
  <exclude-pattern>*/tests/*</exclude-pattern>
</rule>

</ruleset>
````

Except that exclude-pattern issue, things work well. ruleset file is read.

Any idea how to handle that? (I've got a bad tweak but it's gonna exclude some other files that I want to send through phpcs).

**Comment by ajmichels** [comment]
So you are trying to exclude `*.blade.php` that that is not working? Why are you unable to put that into your ruleset?

**Comment by godbout** [comment]
The ````*.blade.php``` exclude works well. It's with this line ````<exclude-pattern>*/tests/*</exclude-pattern>```` that I have problem. Basically it doesn't work. If I replace by ````<exclude-pattern>*Test.php</exclude-pattern>```` it works, but it's gonna fuck some files. Basically, it seems that you can't exclude folders through the plugin, because it phpcs the temporary files from /private/var instead of the real project files.

**Comment by ajmichels** [comment]
Try setting your standard to your config file. Something like this.

```
"linters": {
    "phpcs": {
        ...
        "standard": "${project}/phpcs.xml"
    }
}
```

**Comment by godbout** [comment]
Tried. Same issue.

I have also project settings setup:

````
"SublimeLinter":
    {
        "linters":
        {
            "phpcs":
            {
                "standard": "~/Dropbox/Development/vocabulary-builder/source/phpcs.xml"
            }
        }
    }
````

The problem is not from the config files not being read. They are. The problem is from the fact that the tests are made on the temporary file. See pic below. Hope I'm being more clear now.

<img width="1150" alt="create_blade_php_ _vocabulary-builder" src="https://user-images.githubusercontent.com/121373/29321371-cdd235bc-820c-11e7-972c-19a1db4f1b30.png">

**Comment by ajmichels** [comment]
[According to the documentation](http://www.sublimelinter.com/en/latest/linter_attributes.html#tempfile-suffix) for Sublime Linter (the framework that this project uses), the temp files are used in situations where the "linter executables... cannot receive input from stdin." As far as I can tell, this is not the situation with PHPCS. That being said this linter project (SublimeLinter-phpcs) has been using the temp files [since it was first introduced](https://github.com/SublimeLinter/SublimeLinter-phpcs/blob/12ff214bb346369b949bff76641bcec2d4f07bb5/linter.py#L36). Perhaps @hd-deman could shed some light on why that is.

It appears the solution to the problem you are encountering would be for `temfile_sufix` to be set to `-` [as described in the documentation](http://www.sublimelinter.com/en/latest/linter_attributes.html#file-only-linters).

**Comment by ajmichels** [comment]
Making the change to `tempfile_suffix = 'php'` does not come without consequence. As stated in the documentation "File-only linters will only run on files that have not been modified since their last save, ensuring that what the user sees and what the linter executable sees is in sync."

Given that this would be such a big impact for a lot of people I think it would be necessary for this to be configurable. A user of the plugin should be able to decide if they want to be required to save their files before the linter will run.

**Comment by godbout** [comment]
I see. Thanks for the info @ajmichels. Currently, can you confirm that basically this linter doesn't handle the folders in exclude-pattern and it's not just me that is doing something wrong?
If I understand correctly, this has to be modified (or better, added as option) in this linter, right?

**Comment by ajmichels** [comment]
Yes. I would say your summary is accurate.

**Comment by godbout** [comment]
Great. Thanks for the help and clarification. Time to learn python now 😂️

**Comment by kaste** [comment]
We switched to linting via stdin with version 2.1 of this plugin. Closing bc this should resolve the issue.
