### ISSUE TITLE
Custom Coding Standard

### ISSUE THREAD

**Issue by robertmain** [SublimeLinter/SublimeLinter-phpcs#3]
Hi there

I'm passing in the path to my PHP Code Sniffer ruleset into SublimeLinter-phpcs like so:
```json
{
    "user": {
        "linters": {
            "phpcs": {
                "standard": "C:/Users/%USERNAME%/Documents/phpcs-ruleset.xml"
            }
        }
    }
}
```

I just wanted to make sure that this is valid and that my code is in fact linting to the standard that I think it is.

**Comment by samheuck** [comment]
I second this - how do you specify a custom standard? I've tried a few combinations to no avail - the only standards that seem to work are the ones that come with php-code-sniffer.

**Comment by robertmain** [comment]
Just pass in the path to the xml standard. Worked for me (and the everyone
I work with that uses sublime)

**Comment by samheuck** [comment]
Okay - must be something wrong with the standard I'm trying to use.

**Comment by robertmain** [comment]
Could be... Have a look in the sublime console (View > Show Console) - that
should tell you what's up

**Comment by samheuck** [comment]
Yeah I found it - the standard I was trying to use is Drupal - but I was using a slightly older version of the standard that is not compatible with the latest version php-code-sniffer.

Sorry to bug you about it. Thanks for the response.

--Sam

**Comment by robertmain** [comment]
Not a problem, glad you got sorted out :-)

**Comment by sebastienbarre** [comment]
I'm a bit confused about it as well.

Ideally, I would like the plugin to behave like `phpcs` when I run it from the command-line in my project directory: it looks for a `phpcs.xml` file automatically in the current directory and its parent directories. This is where I put all the custom rules for that specific project.

Is there a way for the plugin to do the same? i.e., look for any `phpcs.xml` file in the directory of the current file and its parent directories and use it to validate the current file? And if not found, use the `standard:` option found in the Linter settings? I can't put the full-path to the `phpcs.xml` file in the SublimeLinter-phpcs settings key because there is one per project.

Thanks

**Comment by sebastienbarre** [comment]
**Update:** I found the solution, here it, in case somebody stumble upon the same issue.

See "PHPCS Config File" in [PHP_CodeSniffer 2.2.0 released](http://www.squizlabs.com/php-codesniffer/2.2.0-released) and [Advanced Usage · Using a Default Configuration File](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file)
> If you run PHP_CodeSniffer without specifying a coding standard, PHP_CodeSniffer will look in the current directory, and all parent directories, for a file called either phpcs.xml or phpcs.xml.dist. If found, configuration information will be read from this file, including the files to check, the coding standard to use, and any command line arguments to apply.

However this will not work:
```json
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "standard": "phpcs.xml"
            }
```
If I look at the console in Debug mode:
```
SublimeLinter: phpcs: Project.php ['/Volumes/Users/barre/.composer/vendor/bin/phpcs', '--report=checkstyle', '--standard=phpcs.xml'] 
SublimeLinter: phpcs output:
ERROR: the "phpcs.xml" coding standard is not installed. The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend 
```
The issue here is that ``--standard=phpcs.xml`` is passed. The solution is to specify an empty value for the standard.
```json
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "standard": ""
            }
```
and then `phpcs` will look for `phpcs.xml` automatically in the current dir or its parent directories.

**Comment by ajmichels** [comment]
Seems like this issue can be close.

**Comment by bcalik** [comment]
@sebastienbarre Ah thanks! I've been struggling with this issue for hours.
