### ISSUE TITLE
More than 1 minute needed for linting....

### ISSUE THREAD

**Issue by Pictor13** [SublimeLinter/SublimeLinter-phpcs#47]
I have a case where **the linting of php files gets updated just after about 1 minute**.
It happens to me when providing an *anonymous function* as parameter to a function-A, and the anonymous function should have a `use`-clause to include some vars.

When I add the `use`-clause, **after a minute** I get a linting error on the closing bracket of the function-A, saying it should have minimum 16 spaces for indentation instead of 8
(that makes no sense; in fact, when adding the spaces as requested, then it gives me the opposite error, saying I should have 8 spaces. Feels like a bug in `phpcs`).

When I try to see what improves, removing the `use`-clause, **I need to wait another minute before seeing the linting error disappear**.

On other PHP files the linting is super fast as usual. But if I go in the file with the anonymous function, try to save, and then provoking a linting error in a file that previously was working fine, now the linting get stuck for a minute also in there.
(and after that minute, it will come back super fast as usual; as long as I don't trigger linting in the file with the anonymous function.

That is pretty insane. And there is not even a high CPU load, everything is fine and calm.
Also, I would highlight the fact that I using the (pretty buggy, sluggish, crashy) latest version of SublimeText (3.2.1, Build 3207).

**Comment by kaste** [comment]
Can you reproduce it on the command line? Also make sure to enable debug in the SublimeLinter settings, then open Sublime's console, and watch the show.

**Comment by braver** [comment]
What I personally get is that loads of processes are spinned up because the selector is no good. It can't actually deal with html files and I don't really understand why it's the default selector. For the projects I work on, with the default PHP syntax the selector doesn't even work. It does work when I set the selector to `'embedding.php'`, because the root selector for a PHP file isn't actually `'source.php'`. That solves the performance and reliability issues for me.
I don't really know about all the different kinds of setups with PHP to decide we should to change the default selector though.
